2023-11-19 11:17:54,450 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-11-19 11:17:54,450 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Configure stats pid to 3648
2023-11-19 11:17:54,450 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Fede\.config\wandb\settings
2023-11-19 11:17:54,450 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Fede\Desktop\Art\Not_Transfer_learning_models\wandb\settings
2023-11-19 11:17:54,450 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-19 11:17:54,450 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-19 11:17:54,451 INFO    MainThread:3648 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Fede\Desktop\Art\Not_Transfer_learning_models\wandb\run-20231119_111754-eia85dvl\logs\debug.log
2023-11-19 11:17:54,451 INFO    MainThread:3648 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Fede\Desktop\Art\Not_Transfer_learning_models\wandb\run-20231119_111754-eia85dvl\logs\debug-internal.log
2023-11-19 11:17:54,451 INFO    MainThread:3648 [wandb_init.py:init():564] calling init triggers
2023-11-19 11:17:54,451 INFO    MainThread:3648 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rage': 0.001, 'epochs': 2}
2023-11-19 11:17:54,451 INFO    MainThread:3648 [wandb_init.py:init():588] re-initializing run, found existing run on stack: ubtclrih
2023-11-19 11:17:54,452 INFO    MainThread:3648 [wandb_run.py:_finish():1894] finishing run fede-/Art/ubtclrih
2023-11-19 11:17:54,453 INFO    MainThread:3648 [jupyter.py:save_history():445] not saving jupyter history
2023-11-19 11:17:54,453 INFO    MainThread:3648 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-19 11:17:54,453 INFO    MainThread:3648 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-11-19 11:17:54,453 INFO    MainThread:3648 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2023-11-19 11:17:54,453 INFO    MainThread:3648 [wandb_run.py:_restore():2111] restore
2023-11-19 11:17:54,453 INFO    MainThread:3648 [wandb_run.py:_restore():2117] restore done
2023-11-19 11:17:58,569 INFO    MainThread:3648 [wandb_run.py:_footer_history_summary_info():3481] rendering history
2023-11-19 11:17:58,569 INFO    MainThread:3648 [wandb_run.py:_footer_history_summary_info():3513] rendering summary
2023-11-19 11:17:58,572 INFO    MainThread:3648 [wandb_run.py:_footer_sync_info():3440] logging synced files
2023-11-19 11:17:58,688 INFO    MainThread:3648 [wandb_init.py:init():613] starting backend
2023-11-19 11:17:58,688 INFO    MainThread:3648 [wandb_init.py:init():617] setting up manager
2023-11-19 11:17:58,690 INFO    MainThread:3648 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-11-19 11:17:58,690 INFO    MainThread:3648 [wandb_init.py:init():623] backend started and connected
2023-11-19 11:17:58,699 INFO    MainThread:3648 [wandb_run.py:_label_probe_notebook():1234] probe notebook
2023-11-19 11:17:58,699 INFO    MainThread:3648 [wandb_run.py:_label_probe_notebook():1244] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-11-19 11:17:58,699 INFO    MainThread:3648 [wandb_init.py:init():714] updated telemetry
2023-11-19 11:17:58,736 INFO    MainThread:3648 [wandb_init.py:init():747] communicating run to backend with 60.0 second timeout
2023-11-19 11:18:00,032 INFO    MainThread:3648 [wandb_run.py:_on_init():2180] communicating current version
2023-11-19 11:18:00,158 INFO    MainThread:3648 [wandb_run.py:_on_init():2189] got version response upgrade_message: "wandb version 0.16.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-11-19 11:18:00,158 INFO    MainThread:3648 [wandb_init.py:init():798] starting run threads in backend
2023-11-19 11:18:00,251 INFO    MainThread:3648 [wandb_run.py:_console_start():2159] atexit reg
2023-11-19 11:18:00,251 INFO    MainThread:3648 [wandb_run.py:_redirect():2014] redirect: wrap_raw
2023-11-19 11:18:00,251 INFO    MainThread:3648 [wandb_run.py:_redirect():2079] Wrapping output streams.
2023-11-19 11:18:00,251 INFO    MainThread:3648 [wandb_run.py:_redirect():2104] Redirects installed.
2023-11-19 11:18:00,252 INFO    MainThread:3648 [wandb_init.py:init():839] run started, returning control to user process
2023-11-19 11:24:16,580 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-11-19 11:24:16,580 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Configure stats pid to 3648
2023-11-19 11:24:16,580 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Fede\.config\wandb\settings
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Fede\Desktop\Art\Not_Transfer_learning_models\wandb\settings
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Fede\Desktop\Art\Not_Transfer_learning_models\wandb\run-20231119_112416-xcag7gf7\logs\debug.log
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Fede\Desktop\Art\Not_Transfer_learning_models\wandb\run-20231119_112416-xcag7gf7\logs\debug-internal.log
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001DA3636DBD0>
2023-11-19 11:24:16,581 INFO    MainThread:3648 [wandb_init.py:init():564] calling init triggers
2023-11-19 11:24:16,582 INFO    MainThread:3648 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rage': 0.001, 'epochs': 2}
2023-11-19 11:24:16,582 INFO    MainThread:3648 [wandb_init.py:init():588] re-initializing run, found existing run on stack: eia85dvl
2023-11-19 11:24:16,583 INFO    MainThread:3648 [wandb_run.py:_finish():1894] finishing run fede-/Art/eia85dvl
2023-11-19 11:24:16,583 INFO    MainThread:3648 [wandb_run.py:_atexit_cleanup():2128] got exitcode: 0
2023-11-19 11:24:16,583 INFO    MainThread:3648 [wandb_run.py:_restore():2111] restore
2023-11-19 11:24:16,583 INFO    MainThread:3648 [wandb_run.py:_restore():2117] restore done
2023-11-19 11:24:20,347 INFO    MainThread:3648 [wandb_run.py:_footer_history_summary_info():3481] rendering history
2023-11-19 11:24:20,347 INFO    MainThread:3648 [wandb_run.py:_footer_history_summary_info():3513] rendering summary
2023-11-19 11:24:20,350 INFO    MainThread:3648 [wandb_run.py:_footer_sync_info():3440] logging synced files
